id: 657f982be40a43e0a87fe4ef59bbaeb9
initial_creation_type: ocr
source_metadata:
  volumes:
    297a9ba2de1a4e61a02a86a2487b649e:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: ''
      total_pages: 1586
      volume_number: 24
