id: D88823B88
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T08:57:10+00:00'
last_modified: '2022-05-26T10:51:31.634158+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '3114':
      image_group_id: I1PD95869
      title: པདྨ་གཤིན་རྗེ་གཤེད་ཤེས་རབ་བདེ་བ་ཅན་གྱི་སྒྲུབ་ཐབས།
      total_pages: 1586
      order: 24
      base_file: 3114.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
